[project]
name = "alzheimers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "monai>=1.4.0",
    "pydicom>=3.0.1",
    "pylibjpeg-libjpeg>=2.2.0",
    "pylibjpeg>=2.0.1",
]
